service: ms-tracing

plugins:
  - serverless-webpack

configValidationMode: error
variablesResolutionMode: 20210326

custom:
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.stage}-uff
  region: us-east-1
  awsId: 880994143713
  stackName: ${self:service}-${self:custom.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  #authorizer:
    #name: user-manager-authorizer
    #arn: arn:aws:cognito-idp:us-east-1:880994143713:userpool/us-east-1_rQlfwSLAc
    #identitySource: method.request.header.Authorization


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  lambdaHashingVersion: 20201221
  environment:
    transactionTable: ${self:service}-${self:custom.stage}-transaction-table
    requestTable: ${self:service}-${self:custom.stage}-request-table
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action: "*"
  #     Resource:
  #       - arn:aws:dynamodb:*:*:table/${self:provider.environment.transactionTable}
  #       - arn:aws:dynamodb:*:*:table/${self:provider.environment.requestTable}


package:
  patterns:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  - ${file(sls/functions/request.yml)}
  - ${file(sls/functions/transaction.yml)}

resources:
  - ${file(sls/resources/transactionTable.yml)}
  - ${file(sls/resources/requestTable.yml)}