service: ms-tracing

plugins:
  - serverless-webpack

configValidationMode: error
variablesResolutionMode: 20210326

custom:
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'default'}
  region: ${opt:region, 'us-east-1'}
  awsId: 'YOUR_ACCOUNT_ID'
  stackName: ${self:service}-${self:custom.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  #authorizer:
    #name: 'name'
    #arn: 'arn'
    #identitySource: method.request.header.Authorization


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  lambdaHashingVersion: 20201221
  environment:
    transactionTable: ${self:service}-${self:custom.stage}-transaction-table
    requestTable: ${self:service}-${self:custom.stage}-request-table
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.transactionTable}/*
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.requestTable}/*
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.transactionTable}
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.requestTable}


package:
  patterns:
    - '!node_modules/**'

functions:
  - ${file(sls/functions/request.yml)}
  - ${file(sls/functions/transaction.yml)}

resources:
  - ${file(sls/resources/transactionTable.yml)}
  - ${file(sls/resources/requestTable.yml)}