Resources:
  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.transactionTable}
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: elapsedTime
          AttributeType: N
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: statusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: elapsedTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: elapsedTimeIndex
          KeySchema:
            - AttributeName: createdAt
              KeyType: HASH
            - AttributeName: elapsedTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
